#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <sys/resource.h> 
#include "sep.h"
#include "show.h"

// This module simulates the Verifier
// It receives an anonymous Zero-Knowledge Proof (.bin file) from the Prover.
// Its sole purpose is to mathematically validate the proof over Module-SIS/LWE 
// lattices without ever accessing the user's real identity or private keys.


// AUXILIARY FUNCTIONS FOR DISK DESERIALIZATION
// Reconstructs dynamic FLINT multi-dimensional polynomials from raw binary data.

/*
 * Load the proof polynomial (poly_qshow) from the disk.
 * Zero-knowledge proofs (SHOW scheme) operate in an algebraically distinct field,
 * so this function uses its own parameter for the polynomial's degree (PARAM_N_SHOW).
 */
void load_poly_qshow(FILE *f, poly_qshow p) {
    for (size_t n = 0; n < PARAM_N_SHOW; n++) {
        int64_t c; 
        if (fread(&c, sizeof(int64_t), 1, f) != 1) {
            fprintf(stderr, "Error: Failed to read polynomial coefficient from file.\n");
            exit(EXIT_FAILURE);
        }
        poly_qshow_set_coeff(p, n, c);
    }
}

/*
 * Serializes a complex matrix of ZKP polynomials (K x K).
 * Iterates over all rows and columns of the matrix. 
 * Access via the arrow operator (->) ensures correct dereferencing of dynamically allocated vectors within the FLINT library, 
 * Protection against memory access errors 
 */
void load_mat_k_k(FILE *f, poly_qshow_mat_k_k m) {
    for(size_t i=0; i<PARAM_K_SHOW; i++)
        for(size_t j=0; j<PARAM_K_SHOW; j++)
            load_poly_qshow(f, m[0].rows[i]->entries[j]); // Changed dot to arrow
}

// Interface mapped to the Python Backend Orchestrator
int main(int argc, char *argv[]) {
    // The Verifier expects exactly 1 argument: The path to the anonymous ZKP binary
    if (argc != 2) {
	printf("{\"status\": \"error\", \"message\": \"Usage: ./verify_proof <input_proof.bin>\"}\n");
        return 1;
    }
    //Saving the path to a transport file generated by Python
    char *proof_path = argv[1];
    
    // Initialize the algebraic backend (FLINT) for lattice operations
    arith_setup();
    
    // Variables for performance benchmarking
    struct timespec start, end;
    double time_verify_total_ms = 0.0;
    double time_recon_ms = 0.0;
    double time_verify_math_ms = 0.0;
    double time_ram_ms = 0.0;

    // Initialize an empty structure to hold the incoming proof
    show_proof_t proof; 
    show_proof_init(&proof);
 
    //RAM memory allocation 
    //The verifier must verify the validity of the proof against the system's public parameters
    poly_qshow_vec_k u_embed[PARAM_D];
    poly_qshow_mat_k_k A_embed[PARAM_D][PARAM_D], B_embed[PARAM_D][PARAM_D*PARAM_K], A3_embed[PARAM_D][PARAM_K];
    poly_qshow_mat_k_k D_embed[PARAM_D][PARAM_M], Ds_embed[PARAM_D][2*PARAM_D];
    
    //Seeds required for randomness and public key reconstruction
    uint8_t crs_seed[CRS_SEED_BYTES]; // Common Reference String (Ensures non-interactivity)
    uint8_t upk_seed[SEED_BYTES]; // Anonymized User Public Key Seed

    
    clock_gettime(CLOCK_MONOTONIC, &start);

    // Physical memory allocation for huge polynomial matrices in the FLINT library
    for (int i = 0; i < PARAM_D; i++) {
        poly_qshow_vec_k_init(u_embed[i]);
        for (int j = 0; j < PARAM_D; j++) { 
            poly_qshow_mat_k_k_init(A_embed[i][j]); 
            poly_qshow_mat_k_k_init(Ds_embed[i][j]); 
            poly_qshow_mat_k_k_init(Ds_embed[i][j + PARAM_D]); 
        }
        for (int j = 0; j < PARAM_D*PARAM_K; j++) poly_qshow_mat_k_k_init(B_embed[i][j]);
        for (int j = 0; j < PARAM_K; j++) poly_qshow_mat_k_k_init(A3_embed[i][j]);
        for (int j = 0; j < PARAM_M; j++) poly_qshow_mat_k_k_init(D_embed[i][j]);
    }

    clock_gettime(CLOCK_MONOTONIC, &end);
    time_ram_ms = (end.tv_sec - start.tv_sec) * 1000.0 + (end.tv_nsec - start.tv_nsec) / 1000000.0;
    
    //AUTHORITY PUBLIC KEY MEASUREMENT
    // Verifier checks the size of the Authority's Master PK to benchmark the ratio between Key size and Proof size.
    long pk_size_bytes = 0;
    FILE *fpk_size = fopen("/home/lac/_build/public_key.bin", "rb");
    if (fpk_size) {
        fseek(fpk_size, 0, SEEK_END);
        pk_size_bytes = ftell(fpk_size);
        fclose(fpk_size);
    } 

    // Verifier loads the anonymous ZKP binary from disk into RAM
    clock_gettime(CLOCK_MONOTONIC, &start);    

    FILE *fin = fopen(proof_path, "rb"); 
    if (!fin) { 
        printf("{\"status\": \"error\", \"message\": \"Proof for %s not found!\"}\n", proof_path); 
        return 1; 
    }
	
    // Load public parameters:
    // - crs_seed: Ensures the Fiat-Shamir heuristic was not tampered with.
    // - upk_seed: Necessary to reconstruct the statemen
    if (fread(crs_seed, 1, CRS_SEED_BYTES, fin) != CRS_SEED_BYTES) {
        printf("{\"status\": \"error\", \"message\": \"Failed to read crs_seed!\"}\n");
        fclose(fin);
        return 1;
    }
	
    if (fread(upk_seed, 1, SEED_BYTES, fin) != SEED_BYTES) {
        printf("{\"status\": \"error\", \"message\": \"Failed to read upk_seed!\"}\n");
        fclose(fin);
        return 1;
    }
   
    // Reconstruction of the Public Statement (Matrix definitions)
    for (int i = 0; i < PARAM_D; i++) {
        for(size_t k=0; k<PARAM_K_SHOW; k++) load_poly_qshow(fin, u_embed[i][0].entries[k]);
          for (int j = 0; j < PARAM_D; j++) { 
            load_mat_k_k(fin, A_embed[i][j]); 
            load_mat_k_k(fin, Ds_embed[i][j]); 
            load_mat_k_k(fin, Ds_embed[i][j + PARAM_D]); 
        }
        for (int j = 0; j < PARAM_D*PARAM_K; j++) load_mat_k_k(fin, B_embed[i][j]);
        for (int j = 0; j < PARAM_K; j++) load_mat_k_k(fin, A3_embed[i][j]);
        for (int j = 0; j < PARAM_M; j++) load_mat_k_k(fin, D_embed[i][j]);
    }

    // Reconstruction of the Pure Zero-Knowledge Proof
    // The variables z1, z2, z3 are blinded vectors hiding the secret key and signature.
    for(size_t i=0; i<PARAM_D_SHOW; i++) load_poly_qshow(fin, proof.tA[0].entries[i]);
    for(size_t i=0; i<PARAM_ARP_DIV_N_L_SHOW; i++) load_poly_qshow(fin, proof.tB[0].entries[i]);
    
    if (fread(proof.z3, sizeof(coeff_qshow), PARAM_ARP_SHOW, fin) != PARAM_ARP_SHOW) {
        printf("{\"status\": \"error\", \"message\": \"Failed to read proof.z3!\"}\n");
        fclose(fin);
        return 1;
    }
    
    for(size_t i=0; i<PARAM_L_SHOW; i++) load_poly_qshow(fin, proof.h[0].entries[i]);
    load_poly_qshow(fin, proof.t1);
    
    // Load the Challenge (c) - The core element of the Fiat-Shamir transformation
    load_poly_qshow(fin, proof.c); 

    if (fread(&proof.ctr_c, sizeof(uint32_t), 1, fin) != 1) {
        printf("{\"status\": \"error\", \"message\": \"Failed to read proof.ctr_c!\"}\n");
        fclose(fin);
        return 1;
    }
    
    // Load the Masked Secrets
    for(size_t i=0; i<PARAM_M1_SHOW; i++) load_poly_qshow(fin, proof.z1[0].entries[i]);
    for(size_t i=0; i<PARAM_M2_SHOW; i++) load_poly_qshow(fin, proof.z2[0].entries[i]);

    //close the file
    fclose(fin);
    clock_gettime(CLOCK_MONOTONIC, &end);
    time_recon_ms = (end.tv_sec - start.tv_sec) * 1000.0 + (end.tv_nsec - start.tv_nsec) / 1000000.0;
    
    // MATHEMATICAL VERIFICATION
    // The Verifier performs a series of polynomial multiplications in the ring.
    // It verifies if the blinded vectors match the public statement given the challenge.
    clock_gettime(CLOCK_MONOTONIC, &start);

    // returns 1 (True) if mathematically valid, 0 (False) if tampered or invalid.
    int is_valid = show_verify(&proof, A_embed, B_embed, A3_embed, Ds_embed, D_embed, u_embed, crs_seed, upk_seed);
    
    clock_gettime(CLOCK_MONOTONIC, &end);
    time_verify_math_ms = (end.tv_sec - start.tv_sec) * 1000.0 + (end.tv_nsec - start.tv_nsec) / 1000000.0;

    // Total verification time = RAM setup + I/O Load + Math Verify
    time_verify_total_ms = time_ram_ms + time_recon_ms + time_verify_math_ms;

    // Interrogates the Linux OS to find the Maximum Resident Set Size (Peak RAM)
    struct rusage usage;
    getrusage(RUSAGE_SELF, &usage);
    long peak_ram_kb = usage.ru_maxrss; // Max memory allocated by the OS in Kilobytes

    //Pass execution metrics back to the Python backend via JSON stdout
    if (is_valid) {
        printf("{\"status\": \"success\", \"is_valid\": true, \"message\": \"The ZKP has been mathematically verified!\", \"time_verify_total_ms\": %.3f, \"time_ram_ms\": %.3f, \"time_recon_ms\": %.3f, \"time_verify_math_ms\": %.3f, \"pk_size_bytes\": %ld, \"peak_ram_kb\": %ld}\n", 
               time_verify_total_ms, time_ram_ms, time_recon_ms, time_verify_math_ms, pk_size_bytes, peak_ram_kb);
    } else {
        printf("{\"status\": \"success\", \"is_valid\": false, \"message\": \"ZKP failed!\", \"time_verify_total_ms\": %.3f, \"time_ram_ms\": %.3f, \"time_recon_ms\": %.3f, \"time_verify_math_ms\": %.3f, \"pk_size_bytes\": %ld, \"peak_ram_kb\": %ld}\n", 
               time_verify_total_ms, time_ram_ms, time_recon_ms, time_verify_math_ms, pk_size_bytes, peak_ram_kb);
    } 

    //Clear all large arrays from RAM.
    arith_teardown();
    return 0;
}